### ISSUE TITLE
Add a shortcut to activate streamlink

### ISSUE THREAD

**Issue by cajeiri** [canaltinova/Twitch-Live#7]
Hey, 

Would it be possible to add, in a future version, the option to open the streams with streamlink? (It's the continuation of the now dead livestreamer).

More info here:  https://github.com/streamlink/streamlink

**Comment by canova** [comment]
Hi,
Generally add-ons have a limited access to OS, but I'll look into it, if there is a way to implement it. Thanks for your feedback!
